### ISSUE TITLE
Doesn't compile on gcc 5

### ISSUE THREAD

**Issue by PoisonedMelon** [fellon/cosMUD#1]
Many errors attempting to compile on recent versions of gcc, i believe this also affects gcc 4.

**Comment by PoisonedMelon** [comment]
Fixed by my recent commits, i did it wrong. Should have forked it and made a pull request i think. I have only updated Dev. Also I think these directories should be git branches, but that's another issue.

**Comment by fellon** [comment]
Well played Sir!  I actually have the code up on an openbsd box and debugging compile errors. I'll see if I can correct the repos and grab a copy of your changes.
